### ISSUE TITLE
Update to node 10.x

### ISSUE THREAD

**Issue by samjeffress** [shelfio/aws-lambda-brotli-unpacker#57]
AWS lambda now supports node 10.x, and we'd love to upgrade :)

It might be good to support multiple runtimes at once and use `process.version` to detemine which one to use in https://github.com/shelfio/aws-lambda-brotli-unpacker/blob/master/src/iltorb/index.js#L8 or to require a peer dependency (not really sure if this is feasable).

If you're happy with one of those solutions I'm happy to implement it.

Thanks for your work!

Sam

**Comment by vladgolubev** [comment]
Hey @samjeffress!

This sounds awesome, I'd like to upgrade some time in the future as well!

`process.version` is ok, but it means there always will be 2 versions of `itorb`.

What about creating a new major version which works with node 10.x only?

Anyway, I'd be glad to see any contributions!

**Comment by aaronsturm** [comment]
I think a new major version that works with 10.x only would definitely be acceptable, especially since Node 8's EOL is coming up.

**Comment by samjeffress** [comment]
I've created a pr #65, I'll need some more time to do some testing to make sure it actually works :)

**Comment by mrvisser** [comment]
I've created #83 (tests) and #84 (upgrade to 10.x + native brotli) to address comments in https://github.com/shelfio/aws-lambda-brotli-unpacker/pull/65 .

**Comment by vladgolubev** [comment]
[v1.0.0](https://github.com/shelfio/aws-lambda-brotli-unpacker/releases/tag/v1.0.0) is published which supports Node 10.x & 12.x
